#!/usr/bin/env python3

"""
TODO:

- Experiment with id compression
"""

import json
import sys
import pathlib
import cbor2
import datetime
import re
import hashlib

class Schema:
    labels = {}
    enums = {}
    consts = {}

    def __init__(self, schema_path: pathlib.Path):
        for line in schema_path.read_text().splitlines():
            line = line.strip()
            if line.startswith("label."):
                label, value = line[len("label.") :].split("=")
                self.labels[label.strip()] = int(value.strip())
            elif line.startswith("const."):
                const, value = line[len("const.") :].split("=")
                self.consts[const.strip()] = value.strip()
        # SPDX generated by microsoft/sbom-tool still appears to use
        # SPDX-2.2 constants, so this is a workaround to map them correctly.
        spdx_2_2_consts = {}
        for const, value in self.consts.items():
            spdx_2_2_consts[re.sub("([A-Z])", r"_\1", const).upper()] = value
        spdx_2_2_consts["NOASSERTION"] = spdx_2_2_consts["NO_ASSERTION"]
        self.consts.update(spdx_2_2_consts)

class InternedStrings:
    def __init__(self, offset, active):
        self.starting_offset = offset
        self.latest_index = offset
        self.entries = {}
        self.active = active

    def get(self, entry):
        if not self.active:
            return entry
        if len(entry) < 2:
            return entry
        if not entry in self.entries:
            # print(f"Interning string '{entry}' as index {self.latest_index}")
            self.latest_index += 1
            self.entries[entry] = self.latest_index
        return self.entries[entry]

    def reset(self):
        self.latest_index = self.starting_offset
        self.entries = {}
    
INTERNED_STRINGS = InternedStrings(0, True)

def simple_value_convert(key, value, schema):
    if key is not None and key == "hashValue":
        return bytes.fromhex(value)
    if key is not None and (key == "created" or key.endswith("Time")):
        return cbor2.CBORTag(
            1,
            int(
                datetime.datetime.fromisoformat(
                    value.replace("Z", "+00:00")
                ).timestamp()
            ),
        )
    if isinstance(value, str):
        if value in schema.consts:
            return schema.consts[value]
        else:
            # microsoft/sbom-tool uses SPDXRef- prefixed-UUIDs in text that are quite large
            if value.startswith("SPDXRef-"):
                return hashlib.sha256(value.encode("utf-8")).digest()
    return value

def mapped(document, schema):
    map = {}
    for key, value in document.items():
        val = value
        if isinstance(value, dict):
            val = mapped(value, schema)
        elif isinstance(value, list):
            val = [
                mapped(item, schema) if isinstance(item, dict) else simple_value_convert(None, item, schema)
                for item in value
            ]
        converted_value = simple_value_convert(key, val, schema)
        if isinstance(converted_value, str):
            map[schema.labels.get(key, key)] = INTERNED_STRINGS.get(converted_value)
        else:
            map[schema.labels.get(key, key)] = converted_value
    return map


def convert(document_path, schema_path, string_referencing=False):
    document = json.loads(document_path.read_text())
    schema = Schema(schema_path)
    INTERNED_STRINGS.reset()
    mapped_doc = mapped(document, schema)
    if INTERNED_STRINGS.active:
        # print(f"Total interned strings: {len(INTERNED_STRINGS.entries)}")
        mapped_doc[2000] = INTERNED_STRINGS.entries
    return cbor2.dumps(mapped_doc, string_referencing=string_referencing)


if __name__ == "__main__":
    if len(sys.argv) == 4:
        input_path = pathlib.Path(sys.argv[1])
        output_path = pathlib.Path(sys.argv[2])
        schema_path = pathlib.Path(sys.argv[3])
    else:
        print("Usage: conv.py <spdx3.json> <output.cbor> <schema.cddl>")
        sys.exit(1)
    with output_path.open("wb") as fd:
        fd.write(convert(input_path, schema_path))
